#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

hour=0
min=0


while [ $hour -le 12 ]
do

    if [ $hour -eq 0 ]
    then
        echo "Hour: $hour"
        hour=$(( hour + 1 ))
    fi

    min=0
    while [ $min -le 60 ]
    do
        if [ $min -eq 60 ]
        then
            echo "Hour: $hour"
        else
            echo "$min"
        fi
        min=$(( min + 1 ))
    done
    hour=$(( hour + 1 ))
done
