#!/usr/bin/env bash
# Define the key name, key size, and passphrase

KEY_NAME="school"
KEY_SIZE=4096
PASSPHRASE="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b $KEY_SIZE -f $KEY_NAME -N $PASSPHRASE
