#!/usr/bin/env bash
# Configuring ssh client to connect to a server without typing a password.
Host myserver
    HostName 98.98.98.98
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
